// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `events`, `runtime`, `tasks`, `with_server`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Prepares the runtime. Safe to call more than once.
///
/// Called from `main()` before the first frame so that the first transfer does
/// not pay for thread creation.
void initDataPlane() => RustLib.instance.api.crateApiTransferInitDataPlane();

/// The single event stream, consumed once at startup.
///
/// Progress is already throttled on the Rust side, so this delivers roughly ten
/// events per second per active file rather than one per chunk.
Stream<DataPlaneEvent> dataPlaneEvents() =>
    RustLib.instance.api.crateApiTransferDataPlaneEvents();

/// Starts the data-plane listener and returns the port it bound.
///
/// Pass 0 to let the OS choose, then advertise the returned port over the
/// existing presence broadcast.
Future<int> startServer({
  required String certificatePem,
  required String privateKeyPem,
  required int port,
}) => RustLib.instance.api.crateApiTransferStartServer(
  certificatePem: certificatePem,
  privateKeyPem: privateKeyPem,
  port: port,
);

/// Authorises a session, after the control channel has verified the peer and
/// the user has accepted the files.
///
/// Until this is called, a `PUT` carrying the token is answered with 404 — the
/// token is a receipt for a decision made elsewhere, not a credential in itself.
Future<void> openSession({
  required String token,
  required List<IncomingFileSpec> files,
}) => RustLib.instance.api.crateApiTransferOpenSession(
  token: token,
  files: files,
);

/// Retires a session token so it cannot be replayed once the exchange is over.
Future<void> closeSession({required String token}) =>
    RustLib.instance.api.crateApiTransferCloseSession(token: token);

/// Stops listening, letting in-flight writes finish first.
///
/// A hard stop mid-write would leave a partial file with no accurate record of
/// how far it got, which is the one thing resume depends on.
Future<void> stopServer({required int graceMillis}) =>
    RustLib.instance.api.crateApiTransferStopServer(graceMillis: graceMillis);

/// Begins a send and returns immediately with a handle for [`cancel_send`].
///
/// Outcomes arrive on the event stream. Returning a handle rather than a future
/// keeps the call off the isolate for the whole transfer, which for a large file
/// is the difference between a responsive UI and a frozen one.
PlatformInt64 startSend({
  required String baseUrl,
  required String token,
  required String peerFingerprint,
  required List<OutgoingFileSpec> files,
}) => RustLib.instance.api.crateApiTransferStartSend(
  baseUrl: baseUrl,
  token: token,
  peerFingerprint: peerFingerprint,
  files: files,
);

/// Closes a descriptor that was opened for a send which then did not happen.
///
/// [`start_send`] adopts every descriptor it is given, so once a send starts
/// there is nothing here to do. The gap is the send that never starts — this
/// build refusing it, or the caller giving up between opening the file and
/// asking — where the descriptor would otherwise stay open for the life of the
/// process. Dart has no way to close a raw descriptor itself, and this crate
/// already owns the question, so it answers it here.
///
/// Closing a descriptor that was never open, or one already closed, is ignored.
void closeDescriptor({required int fd}) =>
    RustLib.instance.api.crateApiTransferCloseDescriptor(fd: fd);

/// Stops a send. The peer keeps what it already wrote, so a later attempt
/// resumes from there rather than starting over.
void cancelSend({required PlatformInt64 taskId}) =>
    RustLib.instance.api.crateApiTransferCancelSend(taskId: taskId);

/// The fingerprint of a certificate, for the rare case Dart wants Rust's
/// reading of a peer rather than its own. Exposed mainly so the two can be
/// compared in a test on a real device.
String fingerprintOfCertificate({required List<int> certificateDer}) => RustLib
    .instance
    .api
    .crateApiTransferFingerprintOfCertificate(certificateDer: certificateDer);

/// `sending` says which half of a transfer this came from: true for a send this
/// device started, false for a file arriving. A device doing both at once, or a
/// test running both ends in one process, sees them on the same stream and
/// cannot otherwise tell them apart.
///
/// `session` is the token the control channel issued, so Dart can attribute an
/// event without keeping its own map of task ids.
///
/// `transferred` carries the byte count in every case, including the partial
/// length after a failure or a cancellation — which is exactly where a resume
/// would pick up. `message` is empty except on [`DataPlaneEventKind::Failed`].
class DataPlaneEvent {
  final DataPlaneEventKind kind;
  final bool sending;
  final String session;
  final int index;
  final PlatformInt64 transferred;
  final PlatformInt64 total;
  final String message;

  const DataPlaneEvent({
    required this.kind,
    required this.sending,
    required this.session,
    required this.index,
    required this.transferred,
    required this.total,
    required this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      sending.hashCode ^
      session.hashCode ^
      index.hashCode ^
      transferred.hashCode ^
      total.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataPlaneEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sending == other.sending &&
          session == other.session &&
          index == other.index &&
          transferred == other.transferred &&
          total == other.total &&
          message == other.message;
}

/// What happened, for both directions.
///
/// Flat rather than a variant-carrying enum on purpose: that shape would make
/// flutter_rust_bridge generate a freezed union, which means adding `freezed`
/// and a second build_runner pass to an app that already runs one for
/// dart_mappable. The boundary type stays dumb and `lib/transfer/data_plane.dart`
/// turns it into a real sealed class on arrival — Dart 3 needs no codegen for
/// that.
enum DataPlaneEventKind { progress, fileFinished, failed, cancelled }

/// A file this device is about to receive.
///
/// `destination` is an absolute path chosen by Dart. The sender's filename
/// never reaches Rust: `lib/utils/save_path.dart` already sanitises it and
/// resolves collisions, and re-deciding that here would be a second chance to
/// get path traversal wrong.
class IncomingFileSpec {
  final String destination;

  /// Signed because flutter_rust_bridge maps `u64` to Dart's `BigInt` and
  /// `i64` to its plain `int`. A file large enough to overflow this does not
  /// exist. Negative means the caller has a bug and is refused.
  final PlatformInt64 size;

  const IncomingFileSpec({required this.destination, required this.size});

  @override
  int get hashCode => destination.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IncomingFileSpec &&
          runtimeType == other.runtimeType &&
          destination == other.destination &&
          size == other.size;
}

/// A file this device is about to send.
class OutgoingFileSpec {
  /// Absolute path to the file, or empty when [`fd`](Self::fd) carries it.
  final String source;

  /// A descriptor the platform layer already opened, when the file has no
  /// path this process could use.
  ///
  /// The one caller is Android, where anything picked from the gallery, a
  /// documents provider or a share intent is a `content://` URI: a handle
  /// into another app's provider that only the framework can resolve. Dart
  /// asks Kotlin to open it and detach the descriptor, and it arrives here.
  ///
  /// **Ownership passes with it.** Nothing on the Dart or Kotlin side will
  /// close it; adopting it into an `OwnedFd` below is what guarantees it is
  /// closed exactly once, whatever the transfer goes on to do.
  final int? fd;

  /// See [`IncomingFileSpec::size`].
  final PlatformInt64 size;

  const OutgoingFileSpec({required this.source, this.fd, required this.size});

  @override
  int get hashCode => source.hashCode ^ fd.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutgoingFileSpec &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          fd == other.fd &&
          size == other.size;
}
