// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `events`, `runtime`, `tasks`, `with_server`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Prepares the runtime. Safe to call more than once.
///
/// Called from `main()` before the first frame so that the first transfer does
/// not pay for thread creation.
void initDataPlane() => RustLib.instance.api.crateApiTransferInitDataPlane();

/// The single event stream, consumed once at startup.
///
/// Progress is already throttled on the Rust side, so this delivers roughly ten
/// events per second per active file rather than one per chunk.
Stream<DataPlaneEvent> dataPlaneEvents() =>
    RustLib.instance.api.crateApiTransferDataPlaneEvents();

/// Starts the data-plane listener and returns the port it bound.
///
/// Pass 0 to let the OS choose, then advertise the returned port over the
/// existing presence broadcast.
Future<int> startServer({
  required String certificatePem,
  required String privateKeyPem,
  required int port,
}) => RustLib.instance.api.crateApiTransferStartServer(
  certificatePem: certificatePem,
  privateKeyPem: privateKeyPem,
  port: port,
);

/// Authorises a session, after the control channel has verified the peer and
/// the user has accepted the files.
///
/// Until this is called, a `PUT` carrying the token is answered with 404 — the
/// token is a receipt for a decision made elsewhere, not a credential in itself.
Future<void> openSession({
  required String token,
  required List<IncomingFileSpec> files,
}) => RustLib.instance.api.crateApiTransferOpenSession(
  token: token,
  files: files,
);

/// Retires a session token so it cannot be replayed once the exchange is over.
Future<void> closeSession({required String token}) =>
    RustLib.instance.api.crateApiTransferCloseSession(token: token);

/// Stops listening, letting in-flight writes finish first.
///
/// A hard stop mid-write would leave a partial file with no accurate record of
/// how far it got, which is the one thing resume depends on.
Future<void> stopServer({required BigInt graceMillis}) =>
    RustLib.instance.api.crateApiTransferStopServer(graceMillis: graceMillis);

/// Begins a send and returns immediately with a handle for [`cancel_send`].
///
/// Outcomes arrive on the event stream. Returning a handle rather than a future
/// keeps the call off the isolate for the whole transfer, which for a large file
/// is the difference between a responsive UI and a frozen one.
BigInt startSend({
  required String baseUrl,
  required String token,
  required String peerFingerprint,
  required List<OutgoingFileSpec> files,
}) => RustLib.instance.api.crateApiTransferStartSend(
  baseUrl: baseUrl,
  token: token,
  peerFingerprint: peerFingerprint,
  files: files,
);

/// Stops a send. The peer keeps what it already wrote, so a later attempt
/// resumes from there rather than starting over.
void cancelSend({required BigInt taskId}) =>
    RustLib.instance.api.crateApiTransferCancelSend(taskId: taskId);

/// The fingerprint of a certificate, for the rare case Dart wants Rust's
/// reading of a peer rather than its own. Exposed mainly so the two can be
/// compared in a test on a real device.
String fingerprintOfCertificate({required List<int> certificateDer}) => RustLib
    .instance
    .api
    .crateApiTransferFingerprintOfCertificate(certificateDer: certificateDer);

/// `session` is the token the control channel issued, so Dart can attribute an
/// event without keeping its own map of task ids.
///
/// `transferred` carries the byte count in every case, including the partial
/// length after a failure or a cancellation — which is exactly where a resume
/// would pick up. `message` is empty except on [`DataPlaneEventKind::Failed`].
class DataPlaneEvent {
  final DataPlaneEventKind kind;
  final String session;
  final int index;
  final BigInt transferred;
  final BigInt total;
  final String message;

  const DataPlaneEvent({
    required this.kind,
    required this.session,
    required this.index,
    required this.transferred,
    required this.total,
    required this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      session.hashCode ^
      index.hashCode ^
      transferred.hashCode ^
      total.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataPlaneEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          session == other.session &&
          index == other.index &&
          transferred == other.transferred &&
          total == other.total &&
          message == other.message;
}

/// What happened, for both directions.
///
/// Flat rather than a variant-carrying enum on purpose: that shape would make
/// flutter_rust_bridge generate a freezed union, which means adding `freezed`
/// and a second build_runner pass to an app that already runs one for
/// dart_mappable. The boundary type stays dumb and `lib/transfer/data_plane.dart`
/// turns it into a real sealed class on arrival — Dart 3 needs no codegen for
/// that.
enum DataPlaneEventKind { progress, fileFinished, failed, cancelled }

/// A file this device is about to receive.
///
/// `destination` is an absolute path chosen by Dart. The sender's filename
/// never reaches Rust: `lib/utils/save_path.dart` already sanitises it and
/// resolves collisions, and re-deciding that here would be a second chance to
/// get path traversal wrong.
class IncomingFileSpec {
  final String destination;
  final BigInt size;

  const IncomingFileSpec({required this.destination, required this.size});

  @override
  int get hashCode => destination.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IncomingFileSpec &&
          runtimeType == other.runtimeType &&
          destination == other.destination &&
          size == other.size;
}

/// A file this device is about to send.
class OutgoingFileSpec {
  final String source;
  final BigInt size;

  const OutgoingFileSpec({required this.source, required this.size});

  @override
  int get hashCode => source.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutgoingFileSpec &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          size == other.size;
}
