//! Jett's data plane.
//!
//! This crate moves file bytes and nothing else. Discovery, pairing, the
//! signed attestation, verification words and the control-channel WebSocket
//! all stay in Dart.
//!
//! A body is written where it is told, and the only thing crossing into Dart
//! is a progress event ten times a second.

pub mod api;
pub mod client;
pub mod events;
pub mod fingerprint;
pub mod protocol;
pub mod server;
pub mod tls;

// Generated by `flutter_rust_bridge_codegen generate`. Not edited by hand.
mod frb_generated;
