// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct Version: Hashable, CustomStringConvertible {
  var string: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Version? {
    let string: String? = nilOrValue(pigeonVar_list[0])

    return Version(
      string: string
    )
  }
  func toList() -> [Any?] {
    return [
      string
    ]
  }
  static func == (lhs: Version, rhs: Version) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.string, rhs.string)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("Version")
    MessagesPigeonInternal.deepHash(value: string, hasher: &hasher)
  }

  public var description: String {
    return "Version(string: \(String(describing: string)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformFile: Hashable, CustomStringConvertible {
  var uri: String
  var name: String? = nil
  var size: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformFile? {
    let uri = pigeonVar_list[0] as! String
    let name: String? = nilOrValue(pigeonVar_list[1])
    let size: Int64? = nilOrValue(pigeonVar_list[2])

    return PlatformFile(
      uri: uri,
      name: name,
      size: size
    )
  }
  func toList() -> [Any?] {
    return [
      uri,
      name,
      size,
    ]
  }
  static func == (lhs: PlatformFile, rhs: PlatformFile) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.uri, rhs.uri) && MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.size, rhs.size)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PlatformFile")
    MessagesPigeonInternal.deepHash(value: uri, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: size, hasher: &hasher)
  }

  public var description: String {
    return "PlatformFile(uri: \(String(describing: uri)), name: \(String(describing: name)), size: \(String(describing: size)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct APKInfo: Hashable, CustomStringConvertible {
  var name: String
  var packageName: String
  var fileName: String
  var isSystemApp: Bool
  var isSplitApk: Bool
  var icon: FlutterStandardTypedData
  /// Content URI
  var contentUri: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> APKInfo? {
    let name = pigeonVar_list[0] as! String
    let packageName = pigeonVar_list[1] as! String
    let fileName = pigeonVar_list[2] as! String
    let isSystemApp = pigeonVar_list[3] as! Bool
    let isSplitApk = pigeonVar_list[4] as! Bool
    let icon = pigeonVar_list[5] as! FlutterStandardTypedData
    let contentUri = pigeonVar_list[6] as! String

    return APKInfo(
      name: name,
      packageName: packageName,
      fileName: fileName,
      isSystemApp: isSystemApp,
      isSplitApk: isSplitApk,
      icon: icon,
      contentUri: contentUri
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      packageName,
      fileName,
      isSystemApp,
      isSplitApk,
      icon,
      contentUri,
    ]
  }
  static func == (lhs: APKInfo, rhs: APKInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.name, rhs.name) && MessagesPigeonInternal.deepEquals(lhs.packageName, rhs.packageName) && MessagesPigeonInternal.deepEquals(lhs.fileName, rhs.fileName) && MessagesPigeonInternal.deepEquals(lhs.isSystemApp, rhs.isSystemApp) && MessagesPigeonInternal.deepEquals(lhs.isSplitApk, rhs.isSplitApk) && MessagesPigeonInternal.deepEquals(lhs.icon, rhs.icon) && MessagesPigeonInternal.deepEquals(lhs.contentUri, rhs.contentUri)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("APKInfo")
    MessagesPigeonInternal.deepHash(value: name, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: packageName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: fileName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isSystemApp, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isSplitApk, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: icon, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: contentUri, hasher: &hasher)
  }

  public var description: String {
    return "APKInfo(name: \(String(describing: name)), packageName: \(String(describing: packageName)), fileName: \(String(describing: fileName)), isSystemApp: \(String(describing: isSystemApp)), isSplitApk: \(String(describing: isSplitApk)), icon: \(String(describing: icon)), contentUri: \(String(describing: contentUri)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return Version.fromList(self.readValue() as! [Any?])
    case 130:
      return PlatformFile.fromList(self.readValue() as! [Any?])
    case 131:
      return APKInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Version {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformFile {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? APKInfo {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

var messagesPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MessagesPigeonCodecReaderWriter());

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol JettHostApi {
  func getPlatformVersion() throws -> Version
  func getInitialFiles() throws -> [PlatformFile]
  func getAPKs(withSystemApp: Bool) throws -> [APKInfo]
  /// Opens [uri] for reading and hands back a file descriptor.
  ///
  /// Android only, and the reason the native data plane can send at all: a
  /// `content://` URI names a file inside another app's provider, which only
  /// the framework can resolve. Rust cannot open one and Dart can only stream
  /// it back a chunk at a time — which is every byte crossing the platform
  /// channel before any of them reach the wire.
  ///
  /// **Ownership passes to the caller.** The descriptor is detached from the
  /// `ParcelFileDescriptor` that produced it, so nothing on the platform side
  /// will close it; whoever receives it must, on every path including failure
  /// and cancellation, or the process leaks descriptors until it hits its
  /// limit.
  func openFileDescriptor(uri: String) throws -> Int64
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class JettHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `JettHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: JettHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    #if os(iOS)
      let taskQueue = binaryMessenger.makeBackgroundTaskQueue?()
    #else
      let taskQueue: FlutterTaskQueue? = nil
    #endif
    let getPlatformVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.getPlatformVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPlatformVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPlatformVersionChannel.setMessageHandler(nil)
    }
    let getInitialFilesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.getInitialFiles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getInitialFilesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getInitialFiles()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getInitialFilesChannel.setMessageHandler(nil)
    }
    let getAPKsChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.getAPKs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.getAPKs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      getAPKsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let withSystemAppArg = args[0] as! Bool
        do {
          let result = try api.getAPKs(withSystemApp: withSystemAppArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAPKsChannel.setMessageHandler(nil)
    }
    /// Opens [uri] for reading and hands back a file descriptor.
    ///
    /// Android only, and the reason the native data plane can send at all: a
    /// `content://` URI names a file inside another app's provider, which only
    /// the framework can resolve. Rust cannot open one and Dart can only stream
    /// it back a chunk at a time — which is every byte crossing the platform
    /// channel before any of them reach the wire.
    ///
    /// **Ownership passes to the caller.** The descriptor is detached from the
    /// `ParcelFileDescriptor` that produced it, so nothing on the platform side
    /// will close it; whoever receives it must, on every path including failure
    /// and cancellation, or the process leaks descriptors until it hits its
    /// limit.
    let openFileDescriptorChannel = taskQueue == nil
      ? FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.openFileDescriptor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
      : FlutterBasicMessageChannel(name: "dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.openFileDescriptor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec, taskQueue: taskQueue)
    if let api = api {
      openFileDescriptorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uriArg = args[0] as! String
        do {
          let result = try api.openFileDescriptor(uri: uriArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openFileDescriptorChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class FilesStreamHandler: PigeonEventChannelWrapper<[PlatformFile]> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: FilesStreamHandler) {
    var channelName = "dev.flutter.pigeon.com.sangamshrestha.jett.JettEventChannelApi.files"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<[PlatformFile]>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: messagesPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
