// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class Version {
  Version({this.string});

  String? string;

  List<Object?> _toList() {
    return <Object?>[string];
  }

  Object encode() {
    return _toList();
  }

  static Version decode(Object result) {
    result as List<Object?>;
    return Version(string: result[0] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Version || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(string, other.string);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'Version(string: $string)';
  }
}

class PlatformFile {
  PlatformFile({required this.uri, this.name, this.size});

  String uri;

  String? name;

  int? size;

  List<Object?> _toList() {
    return <Object?>[uri, name, size];
  }

  Object encode() {
    return _toList();
  }

  static PlatformFile decode(Object result) {
    result as List<Object?>;
    return PlatformFile(
      uri: result[0]! as String,
      name: result[1] as String?,
      size: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformFile || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(name, other.name) &&
        _deepEquals(size, other.size);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformFile(uri: $uri, name: $name, size: $size)';
  }
}

class APKInfo {
  APKInfo({
    required this.name,
    required this.packageName,
    required this.fileName,
    required this.isSystemApp,
    required this.isSplitApk,
    required this.icon,
    required this.contentUri,
  });

  String name;

  String packageName;

  String fileName;

  bool isSystemApp;

  bool isSplitApk;

  Uint8List icon;

  /// Content URI
  String contentUri;

  List<Object?> _toList() {
    return <Object?>[
      name,
      packageName,
      fileName,
      isSystemApp,
      isSplitApk,
      icon,
      contentUri,
    ];
  }

  Object encode() {
    return _toList();
  }

  static APKInfo decode(Object result) {
    result as List<Object?>;
    return APKInfo(
      name: result[0]! as String,
      packageName: result[1]! as String,
      fileName: result[2]! as String,
      isSystemApp: result[3]! as bool,
      isSplitApk: result[4]! as bool,
      icon: result[5]! as Uint8List,
      contentUri: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! APKInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(packageName, other.packageName) &&
        _deepEquals(fileName, other.fileName) &&
        _deepEquals(isSystemApp, other.isSystemApp) &&
        _deepEquals(isSplitApk, other.isSplitApk) &&
        _deepEquals(icon, other.icon) &&
        _deepEquals(contentUri, other.contentUri);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'APKInfo(name: $name, packageName: $packageName, fileName: $fileName, isSystemApp: $isSystemApp, isSplitApk: $isSplitApk, icon: $icon, contentUri: $contentUri)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is Version) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PlatformFile) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is APKInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return Version.decode(readValue(buffer)!);
      case 130:
        return PlatformFile.decode(readValue(buffer)!);
      case 131:
        return APKInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class JettHostApi {
  /// Constructor for [JettHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  JettHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<Version> getPlatformVersion() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.getPlatformVersion$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as Version;
  }

  Future<List<PlatformFile>> getInitialFiles() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.getInitialFiles$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<PlatformFile>();
  }

  Future<List<APKInfo>> getAPKs({bool withSystemApp = false}) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.getAPKs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[withSystemApp],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<APKInfo>();
  }

  /// Opens [uri] for reading and hands back a file descriptor.
  ///
  /// Android only, and the reason the native data plane can send at all: a
  /// `content://` URI names a file inside another app's provider, which only
  /// the framework can resolve. Rust cannot open one and Dart can only stream
  /// it back a chunk at a time — which is every byte crossing the platform
  /// channel before any of them reach the wire.
  ///
  /// **Ownership passes to the caller.** The descriptor is detached from the
  /// `ParcelFileDescriptor` that produced it, so nothing on the platform side
  /// will close it; whoever receives it must, on every path including failure
  /// and cancellation, or the process leaks descriptors until it hits its
  /// limit.
  Future<int> openFileDescriptor(String uri) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.com.sangamshrestha.jett.JettHostApi.openFileDescriptor$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[uri],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as int;
  }
}

/// Returns a broadcast [Stream] of events from the `files` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<List> files({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel filesChannel = EventChannel(
    'dev.flutter.pigeon.com.sangamshrestha.jett.JettEventChannelApi.files$instanceName',
    pigeonMethodCodec,
  );
  return filesChannel.receiveBroadcastStream().map((dynamic event) {
    return event as List;
  });
}
