import 'dart:convert';
import 'dart:typed_data';

import 'package:basic_utils/basic_utils.dart';
import 'package:crypto/crypto.dart';

/// Deterministic ECDSA, per RFC 6979. The nonce comes from the key and the
/// message rather than a random source.
const _signingAlgorithm = 'SHA-256/DET-ECDSA';

const _curve = 'prime256v1';
const _validityDays = 3650;

/// Certificates larger than this are refused before being parsed, bounding the
/// work done for an unknown peer. A P-256 certificate is a few hundred bytes.
const maxCertificatePemBytes = 8 * 1024;

/// A device's long-lived identity: a keypair, a certificate carrying it, and
/// the fingerprint peers know it by. Holds no global state and touches no
/// storage.
class DeviceKeys {
  final String certificatePem;
  final String privateKeyPem;
  final ECPrivateKey _privateKey;

  /// Identifies this device to peers. See [keyFingerprintOfPem].
  final String fingerprint;

  const DeviceKeys._({
    required this.certificatePem,
    required this.privateKeyPem,
    required ECPrivateKey privateKey,
    required this.fingerprint,
    // ignore: prefer_initializing_formals
  }) : _privateKey = privateKey;

  /// Mints a fresh identity. P-256 rather than RSA, which runs in the
  /// foreground on first launch and can stall it for seconds.
  factory DeviceKeys.generate() {
    final pair = CryptoUtils.generateEcKeyPair(curve: _curve);
    final privateKey = pair.privateKey as ECPrivateKey;
    final publicKey = pair.publicKey as ECPublicKey;

    final csr = X509Utils.generateEccCsrPem(
      {'CN': 'jett'},
      privateKey,
      publicKey,
    );
    final certificate = X509Utils.generateSelfSignedCertificate(
      privateKey,
      csr,
      _validityDays,
    );

    return DeviceKeys.fromPem(
      certificatePem: certificate,
      privateKeyPem: CryptoUtils.encodeEcPrivateKeyToPem(privateKey),
    );
  }

  /// Restores an identity previously generated by [DeviceKeys.generate].
  factory DeviceKeys.fromPem({
    required String certificatePem,
    required String privateKeyPem,
  }) {
    final fingerprint = keyFingerprintOfPem(certificatePem);
    if (fingerprint == null) {
      throw const FormatException('Certificate carries no usable public key');
    }
    return DeviceKeys._(
      certificatePem: certificatePem,
      privateKeyPem: privateKeyPem,
      privateKey: CryptoUtils.ecPrivateKeyFromPem(privateKeyPem),
      fingerprint: fingerprint,
    );
  }

  /// Signs [statement], returning a base64 DER signature.
  String sign(String statement) => CryptoUtils.ecSignatureToBase64(
    CryptoUtils.ecSign(
      _privateKey,
      Uint8List.fromList(utf8.encode(statement)),
      algorithmName: _signingAlgorithm,
    ),
  );
}

/// The fingerprint of the public key carried by [certificatePem], lowercase
/// hex, or null if it cannot be read.
///
/// Over the key, not the whole certificate: a certificate can be reissued for
/// the same key, and since nothing verifies its self-signature, hashing it
/// would let a collision be ground out by editing fields instead of keygen.
String? keyFingerprintOfPem(String certificatePem) {
  if (certificatePem.length > maxCertificatePemBytes) return null;
  try {
    final certificate = X509Utils.x509CertificateFromPem(certificatePem);
    final keyBytes = certificate.tbsCertificate?.subjectPublicKeyInfo.bytes;
    if (keyBytes == null) return null;
    return sha256.convert(hexToBytes(keyBytes)).toString();
  } catch (_) {
    return null;
  }
}

/// As [keyFingerprintOfPem], for a certificate in DER form — which is how one
/// arrives from a TLS handshake.
String? keyFingerprintOfDer(List<int> der) =>
    keyFingerprintOfPem(pemOfDer(der));

/// Confirms [signature] covers [statement] and was made by the key inside
/// [certificatePem], returning that key's fingerprint. Null if it does not
/// hold, or if any part of the input is unusable.
///
/// The certificate is public and proves nothing on its own; the fingerprint
/// means something only because the signature shows possession of the key.
String? verifiedSignerFingerprint({
  required String certificatePem,
  required String signature,
  required String statement,
}) {
  if (certificatePem.length > maxCertificatePemBytes) return null;
  try {
    final certificate = X509Utils.x509CertificateFromPem(certificatePem);
    final keyBytes = certificate.tbsCertificate?.subjectPublicKeyInfo.bytes;
    if (keyBytes == null) return null;

    final publicKey = CryptoUtils.ecPublicKeyFromDerBytes(hexToBytes(keyBytes));
    final valid = CryptoUtils.ecVerifyBase64(
      publicKey,
      Uint8List.fromList(utf8.encode(statement)),
      signature,
      algorithm: _signingAlgorithm,
    );
    if (!valid) return null;

    return sha256.convert(hexToBytes(keyBytes)).toString();
  } catch (_) {
    return null;
  }
}

/// Wraps DER bytes in PEM armour so they can go through the same parser.
String pemOfDer(List<int> der) {
  final body = base64.encode(der);
  final lines = <String>[
    for (var i = 0; i < body.length; i += 64)
      body.substring(i, i + 64 > body.length ? body.length : i + 64),
  ];
  return '-----BEGIN CERTIFICATE-----\n'
      '${lines.join('\n')}\n'
      '-----END CERTIFICATE-----';
}

/// Strips PEM armour back to the DER bytes inside.
Uint8List derOfPem(String pem) => base64.decode(
  pem
      .replaceAll(RegExp(r'-----[A-Z ]+-----'), '')
      .replaceAll(RegExp(r'\s'), ''),
);

Uint8List hexToBytes(String hex) => Uint8List.fromList([
  for (var i = 0; i + 1 < hex.length; i += 2)
    int.parse(hex.substring(i, i + 2), radix: 16),
]);
